[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv

lib_deps =
    ; Arduino TFLite Micro for ESP32 (tanakamasayuki)
    https://github.com/tanakamasayuki/Arduino_TensorFlowLite_ESP32.git

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_MODE=1
